---
Name: myprojectsiteconfig
---
SilverStripe\SiteConfig\SiteConfig:
    extensions:
        - SilverStripe\Lechon\SiteConfigExtension
---
SilverStripe\Core\Injector\Injector:
    ValidatorBackend:
        - SilverWare\Validator\Backends\ParsleyBackend